
# algorithm
population_size: 4

feedback:
  skip_start_frame: 10
  carla_fps: 20
  predict_horizon: 3.0 # seconds

oracle:
  # oracle config
  collision_speed_threshold_ego: 0.01
  collision_speed_threshold_npc: 1.0
  collision_degree: 90.0
  skip_start_frame: 10

mutator:
  perturbation_probability: 0.5
  speed_std: 2.0
  time_std: 0.5
  position_std: 2.0
  lateral_std: 0.5
  
scenario_space:

  map_region_space:
    # T-Junction
    map_name: "san_mateo"
    region_points:
      - [559667.48, 4157903.06]
      - [559742.52, 4157909.33]
      - [559771.16, 4157886.54]
      - [559762.98, 4157794.33]
      - [559737.12, 4157774.33]
      - [559653.62, 4157797.13]
      - [559631.16, 4157834.61]
      - [559646.16, 4157897.11]
      - [559667.48, 4157903.06]
    forbidden_region_points: 
      - [559681.16, 4157857.41]
      - [559701.16, 4157873.34]
      - [559719.86, 4157852.73]
      - [559696.16, 4157833.08]
      - [559676.16, 4157855.48]
      - [559681.16, 4157857.41]

  ego_space:
    num_range:
      - 2
      - 2
    route_length_range:
      - 50.0
      - 200.0
    trigger_time_range:
      - 0.0
      - 5.0

  npc_vehicle_space:
    num_range:
      - 0
      - 5
    route_length_range:
      - 30.0
      - 150.0
    trigger_time_range:
      - 0.0
      - 5.0
    speed_range:
      - 0.2
      - 15.0

  